# Generated by Django 5.2.3 on 2025-07-01 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
                ('uom_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('conversion_to_si', models.DecimalField(decimal_places=4, max_digits=10)),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('user', models.ForeignKey(help_text='User who owns or created this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('costing_method', models.CharField(choices=[('FIFO', 'First In First Out'), ('AVG', 'Average Cost'), ('STD', 'Standard Cost')], default='AVG', max_length=4)),
                ('tracking_method', models.CharField(choices=[('NONE', 'No Tracking'), ('SERIAL', 'Serial Number'), ('BATCH', 'Batch Number')], default='NONE', max_length=6)),
                ('safety_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs_account_id', models.UUIDField(default=uuid.uuid4)),
                ('inventory_account_id', models.UUIDField(default=uuid.uuid4)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('user', models.ForeignKey(help_text='User who owns or created this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.uom')),
            ],
            options={
                'unique_together': {('organization', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductUoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when last updated')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_default_sales', models.BooleanField(default=False)),
                ('is_default_purchase', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(help_text='User who owns or created this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.uom')),
            ],
            options={
                'unique_together': {('product', 'uom')},
            },
        ),
    ]
