# Generated by Django 5.2.3 on 2025-06-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
                ('conversion_to_si', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.UUIDField()),
                ('product_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('costing_method', models.CharField(choices=[('FIFO', 'FIFO'), ('AVG', 'Average'), ('STD', 'Standard')], max_length=15)),
                ('tracking_method', models.CharField(choices=[('NONE', 'None'), ('SERIAL', 'Serial'), ('BATCH', 'Batch')], max_length=15)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cogs_account_id', models.UUIDField()),
                ('inventory_account_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.uom')),
            ],
            options={
                'unique_together': {('organization_id', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductUoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_default_sales', models.BooleanField(default=False)),
                ('is_default_purchase', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.uom')),
            ],
            options={
                'unique_together': {('product', 'uom')},
            },
        ),
    ]
