# Generated by Django 5.2.3 on 2025-06-27 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cogs_account_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_account_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
